### ISSUE TITLE
Remove # from base url

### ISSUE THREAD

**Issue by romatallinn** [fasten-project/fasten-web#41]
At the moment, URL includes an arbitrary # that is not needed in it. The task is to remove it and update all corresponding links.

**Comment by 96RadhikaJadhav** [comment]
@romatallinn I want to work on the issue. Could you please redirect me to the file/link that is to be corrected?

**Comment by romatallinn** [comment]
> @romatallinn I want to work on the issue. Could you please redirect me to the file/link that is to be corrected?

Hi Radhika, for sure. 

So, there is a fairly common problem with deploying React App to Github Pages. The root page of a deployed to Github Pages application is, for example in our case, `fasten-project.github.io/fasten-web`. However, React doesn't like it. It wants to see an empty path (without `fasten-web` as a root page). 

Thus, initially, the application didn't work in deployment. Although I was able to fix the issue with #16 #17 and the application started working, but this annoying `#` appeared in URL.

Therefore, the task is to research the problem a bit deeper and find a perfect solution for it. Although note I might be wrong with the cause of the problem.

I assume there should be some changes in `src/index.tsx` regarding the router used and maybe basename put. Now the router is HashRouter, but there might be other types as well. BrowserRouter, for example. Note that BrowserRouter works locally (doesn't put `#`), but when deployed, it doesn't work due to `fasten-web` in URL.

And finally, note we have our custom domain, which is also something important to remember about.

I hope I explained the issue thoroughly. Ask me questions if you have any. And take your time, the issue is not severe for now. Just keep me updated with it. 

Use Google to get more insight into the problem:
- _react # in url github pages_
- _deploy react to github pages_
- etc.

Something that may help to start:
- [Deploying a create-react-app with routing to GitHub pages](https://medium.com/@bennirus/deploying-a-create-react-app-with-routing-to-github-pages-f386b6ce84c2)
- [How to deploy React App to GitHub Pages](https://dev.to/yuribenjamin/how-to-deploy-react-app-in-github-pages-2a1f)

**Comment by romatallinn** [comment]
@96RadhikaJadhav ok, so I did a quick overlook. I have an assumption. Since we added a custom domain `demo.fasten-project.eu` lately with no additional url path now, simple `BaseRouter` might work. So if you create a trivial PR that has:
1. `<HashRouter basename={"/"}>` is replaced with `<BrowserRouter>` in `src/index.tsx`;
2. `/#/packages/jboss:jbossmq-client/3.2.3` (line 18 in `src/routes/Home/Home.tsx`) replace with `/packages/jboss:jbossmq-client/3.2.3`.

We can test it out. Let me know when you have it. I will review it and try to deploy it for a test.

**Comment by romatallinn** [comment]
Hi @96RadhikaJadhav, any progress on the issue? Will you be able to bring up PR by the end of this week?

**Comment by 96RadhikaJadhav** [comment]
@romatallinn Oops, I missed your mail. Just give me few mins. Will create a PR soon.

**Comment by romatallinn** [comment]
As described in #50:

So far `HashRouter` is seen to be the only viable router for the application. Although `BrowserRouter` now invokes the homepage, any attempt to open the page via sharing the link is impossible due to its nature.

The problem is that Github Pages does not support SPA natively. Thus, `BrowserRouter` fails. With `HashRouter`, undesired `#` is a necessity.

There is a [workaround](https://github.com/rafgraph/spa-github-pages) for `BrowserRouter`, but it is questionable.
